"""
Memory Store — SQLite Persistence with TTL

PATTERN: Repository Pattern + Soft Expiry
==========================================

The Repository Pattern separates storage logic from business logic.
Instead of writing SQL queries everywhere, we have ONE class that
owns all data access. This makes it easy to:
  - Swap databases (SQLite → PostgreSQL) without changing pipeline code
  - Add caching, indexing, or migration logic in one place
  - Test the pipeline without a real database (mock the store)

SOFT EXPIRY:
  Instead of deleting expired memories immediately, we mark them as expired
  and let the consolidation job clean them up later. This is "soft expiry" —
  like moving a file to trash instead of rm -rf.

  Why? Two reasons:
  1. You can recover accidentally expired memories
  2. Batch deletion is more efficient than one-at-a-time

EMBEDDINGS:
  Each memory can have a vector embedding (array of floats).
  These enable semantic search — "find memories similar to this concept"
  even if the exact words don't match.

  Embeddings are generated by sentence-transformers (all-MiniLM-L6-v2 by default).
  This model converts text into 384-dimensional vectors where:
  - Similar meanings → similar vectors (cosine similarity > 0.8)
  - Different meanings → different vectors (cosine similarity < 0.3)

  This is how modern search works: Google, GitHub Copilot, ChatGPT's browse.
"""

import json
import hashlib
import sqlite3
import uuid
import time
from contextlib import contextmanager
import logging
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

from recall_mcp.store.migrations import CURRENT_SCHEMA_VERSION, run_migrations

logger = logging.getLogger(__name__)

_OUTBOX_STATUSES = ("pending", "processing", "retry", "complete", "dead")


@dataclass
class Memory:
    """A single memory entry."""

    id: str
    content: str
    summary: str
    category: str
    tier: str
    key_topics: list[str]
    source: str
    embedding: Optional[bytes]  # serialized numpy array
    created_at: float
    accessed_at: float
    expires_at: Optional[float]  # None = never expires (persist tier)


@dataclass(frozen=True)
class OutboxJob:
    """One leased durable capture-processing job."""

    id: str
    raw_capture_id: str
    event_type: str
    attempts: int
    content: str
    source: str
    project: str
    agent: str
    user_id: Optional[str]
    workspace_id: Optional[str]
    project_id: Optional[str]
    repository_id: Optional[str]
    task_id: Optional[str]
    session_id: Optional[str]
    requested_category: Optional[str]
    requested_tier: Optional[str]
    gate_decision: Optional[str]
    gate_confidence: Optional[float]
    gate_backend: Optional[str]
    gate_fallback_used: Optional[bool]


class MemoryStore:
    """
    SQLite-backed memory store with TTL-based expiry.

    SCHEMA DESIGN:
    - id: UUID for unique identification across instances
    - content: raw text (what was said)
    - summary: extracted summary (what it means)
    - embedding: binary vector for semantic search (384 floats = 1536 bytes)
    - tier: cold/active/persist → controls TTL
    - expires_at: unix timestamp for auto-expiry (NULL = never)
    - accessed_at: for LRU-style promotion during consolidation
    """

    def __init__(
        self,
        db_path: Path,
        cold_ttl: int = 86400,
        active_ttl: int = 2592000,
        persist_ttl: int = -1,
    ):
        self.db_path = db_path
        self.ttl_config = {
            "cold": cold_ttl,  # 1 day
            "active": active_ttl,  # 30 days
            "persist": persist_ttl,  # -1 = forever
        }
        self._init_db()

    @contextmanager
    def _connect(self):
        """Open a transactional connection with enforcement enabled."""
        connection = sqlite3.connect(str(self.db_path))
        connection.execute("PRAGMA foreign_keys=ON")
        connection.execute("PRAGMA busy_timeout=5000")
        try:
            with connection:
                yield connection
        finally:
            connection.close()

    def _init_db(self):
        """Bring the database to the latest supported canonical schema."""
        run_migrations(self.db_path)
        logger.info("Memory store initialized at %s", self.db_path)

    def enqueue_capture(
        self,
        content: str,
        *,
        source: str = "",
        project: str = "",
        agent: str = "",
        user_id: Optional[str] = None,
        workspace_id: Optional[str] = None,
        project_id: Optional[str] = None,
        repository_id: Optional[str] = None,
        task_id: Optional[str] = None,
        session_id: Optional[str] = None,
        category: Optional[str] = None,
        tier: Optional[str] = None,
    ) -> tuple[str, str]:
        """Atomically persist a raw capture and its processing job."""
        now = time.time()
        capture_id = f"mem_{int(now)}_{uuid.uuid4().hex[:6]}"
        job_id = f"outbox_{uuid.uuid4().hex}"
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            conn.execute(
                """
                INSERT INTO raw_captures (
                    id, content, source, project, agent,
                    user_id, workspace_id, project_id, repository_id,
                    task_id, session_id,
                    requested_category, requested_tier,
                    received_at, updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    capture_id,
                    content,
                    source,
                    project,
                    agent,
                    user_id,
                    workspace_id,
                    project_id,
                    repository_id,
                    task_id,
                    session_id,
                    category,
                    tier,
                    now,
                    now,
                ),
            )
            conn.execute(
                """
                INSERT INTO outbox_jobs (
                    id, raw_capture_id, event_type, status, attempts,
                    available_at, created_at, updated_at
                )
                VALUES (?, ?, 'capture.process', 'pending', 0, ?, ?, ?)
                """,
                (job_id, capture_id, now, now, now),
            )
        return capture_id, job_id

    def persist_raw_capture(
        self,
        content: str,
        *,
        source: str = "",
        project: str = "",
        agent: str = "",
    ) -> str:
        """Compatibility wrapper that now creates a durable outbox job."""
        capture_id, _job_id = self.enqueue_capture(
            content, source=source, project=project, agent=agent
        )
        return capture_id

    def claim_outbox_job(
        self,
        *,
        lease_seconds: float,
        job_id: str | None = None,
        now: float | None = None,
    ) -> OutboxJob | None:
        """Atomically claim one due or expired capture-processing job."""
        claimed_at = time.time() if now is None else now
        due = """
            ((j.status IN ('pending', 'retry') AND j.available_at <= ?)
             OR (j.status = 'processing' AND j.lease_expires_at <= ?))
        """
        params: list[object] = [claimed_at, claimed_at]
        if job_id is not None:
            due += " AND j.id = ?"
            params.append(job_id)
        with self._connect() as conn:
            conn.row_factory = sqlite3.Row
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute(
                f"""
                SELECT j.id
                FROM outbox_jobs j
                WHERE {due}
                ORDER BY j.available_at, j.created_at
                LIMIT 1
                """,
                params,
            ).fetchone()
            if row is None:
                return None
            selected_id = str(row["id"])
            conn.execute(
                """
                UPDATE outbox_jobs
                SET status = 'processing', attempts = attempts + 1,
                    lease_expires_at = ?, updated_at = ?
                WHERE id = ?
                """,
                (claimed_at + lease_seconds, claimed_at, selected_id),
            )
            conn.execute(
                """
                UPDATE raw_captures
                SET status = 'processing', updated_at = ?
                WHERE id = (
                    SELECT raw_capture_id FROM outbox_jobs WHERE id = ?
                )
                """,
                (claimed_at, selected_id),
            )
            claimed = conn.execute(
                """
                SELECT
                    j.id, j.raw_capture_id, j.event_type, j.attempts,
                    r.content, r.source, r.project, r.agent,
                    r.user_id, r.workspace_id, r.project_id, r.repository_id,
                    r.task_id, r.session_id,
                    r.requested_category, r.requested_tier,
                    r.gate_decision, r.gate_confidence, r.gate_backend,
                    r.gate_fallback_used
                FROM outbox_jobs j
                JOIN raw_captures r ON r.id = j.raw_capture_id
                WHERE j.id = ?
                """,
                (selected_id,),
            ).fetchone()
        fallback = claimed["gate_fallback_used"]
        return OutboxJob(
            id=str(claimed["id"]),
            raw_capture_id=str(claimed["raw_capture_id"]),
            event_type=str(claimed["event_type"]),
            attempts=int(claimed["attempts"]),
            content=str(claimed["content"]),
            source=str(claimed["source"]),
            project=str(claimed["project"]),
            agent=str(claimed["agent"]),
            user_id=claimed["user_id"],
            workspace_id=claimed["workspace_id"],
            project_id=claimed["project_id"],
            repository_id=claimed["repository_id"],
            task_id=claimed["task_id"],
            session_id=claimed["session_id"],
            requested_category=claimed["requested_category"],
            requested_tier=claimed["requested_tier"],
            gate_decision=claimed["gate_decision"],
            gate_confidence=claimed["gate_confidence"],
            gate_backend=claimed["gate_backend"],
            gate_fallback_used=None if fallback is None else bool(fallback),
        )

    def ensure_capture_memory(
        self,
        job: OutboxJob,
        *,
        gate_decision: str,
        gate_confidence: float,
        gate_backend: str,
        gate_fallback_used: bool,
        category: str,
        tier: str,
    ) -> str:
        """Persist the accepted gate result and provisional memory idempotently."""
        now = time.time()
        ttl = self.ttl_config.get(tier, self.ttl_config["active"])
        expires_at = None if ttl == -1 else now + ttl
        lifecycle_state = {
            "cold": "ephemeral",
            "active": "active",
            "persist": "stable",
        }.get(tier, "active")
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            existing = conn.execute(
                """
                SELECT content, source, project, agent,
                       user_id, workspace_id, project_id, repository_id,
                       task_id, session_id
                FROM memories WHERE id = ?
                """,
                (job.raw_capture_id,),
            ).fetchone()
            expected = (
                job.content,
                job.source,
                job.project,
                job.agent,
                job.user_id,
                job.workspace_id,
                job.project_id,
                job.repository_id,
                job.task_id,
                job.session_id,
            )
            if existing is None:
                conn.execute(
                    """
                    INSERT INTO memories (
                        id, content, summary, category, tier, key_topics,
                        source, embedding, created_at, accessed_at, expires_at,
                        project, agent, processing_status,
                        user_id, workspace_id, project_id, repository_id,
                        task_id, session_id, lifecycle_state
                    )
                    VALUES (
                        ?, ?, ?, ?, ?, '[]', ?, NULL, ?, ?, ?, ?, ?, 'pending',
                        ?, ?, ?, ?, ?, ?, ?
                    )
                    """,
                    (
                        job.raw_capture_id,
                        job.content,
                        job.content[:200],
                        category,
                        tier,
                        job.source,
                        now,
                        now,
                        expires_at,
                        job.project,
                        job.agent,
                        job.user_id,
                        job.workspace_id,
                        job.project_id,
                        job.repository_id,
                        job.task_id,
                        job.session_id,
                        lifecycle_state,
                    ),
                )
            elif tuple(existing) != expected:
                raise ValueError(f"canonical capture mismatch for {job.raw_capture_id}")
            conn.execute(
                """
                UPDATE raw_captures
                SET gate_decision = ?, gate_confidence = ?, gate_backend = ?,
                    gate_fallback_used = ?, memory_id = ?, status = 'processing',
                    error = '', updated_at = ?
                WHERE id = ?
                """,
                (
                    gate_decision,
                    gate_confidence,
                    gate_backend,
                    int(gate_fallback_used),
                    job.raw_capture_id,
                    now,
                    job.raw_capture_id,
                ),
            )
        return job.raw_capture_id

    def record_gate_result(
        self,
        job: OutboxJob,
        *,
        gate_decision: str,
        gate_confidence: float,
        gate_backend: str,
        gate_fallback_used: bool,
    ) -> tuple[str, float, str, bool]:
        """Persist and return the canonical first gate result for a capture."""
        now = time.time()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            cursor = conn.execute(
                """
                UPDATE raw_captures
                SET gate_decision = ?, gate_confidence = ?, gate_backend = ?,
                    gate_fallback_used = ?, error = '', updated_at = ?
                WHERE id = ? AND gate_decision IS NULL
                """,
                (
                    gate_decision,
                    gate_confidence,
                    gate_backend,
                    int(gate_fallback_used),
                    now,
                    job.raw_capture_id,
                ),
            )
            if cursor.rowcount not in (0, 1):
                raise RuntimeError(
                    f"unexpected gate-result update count for {job.raw_capture_id}"
                )
            canonical = conn.execute(
                """
                SELECT gate_decision, gate_confidence, gate_backend,
                       gate_fallback_used
                FROM raw_captures WHERE id = ?
                """,
                (job.raw_capture_id,),
            ).fetchone()
            if canonical is None or canonical[0] is None:
                raise RuntimeError(
                    f"gate result was not persisted for {job.raw_capture_id}"
                )
        return (
            str(canonical[0]),
            float(canonical[1]),
            str(canonical[2]),
            bool(canonical[3]),
        )

    def complete_skipped_outbox_job(
        self,
        job: OutboxJob,
        *,
        gate_decision: str,
        gate_confidence: float,
        gate_backend: str,
        gate_fallback_used: bool,
    ) -> None:
        """Atomically persist a skip result and complete its outbox job."""
        now = time.time()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            conn.execute(
                """
                UPDATE raw_captures
                SET gate_decision = ?, gate_confidence = ?, gate_backend = ?,
                    gate_fallback_used = ?, status = 'skipped', memory_id = NULL,
                    error = '', updated_at = ?
                WHERE id = ?
                """,
                (
                    gate_decision,
                    gate_confidence,
                    gate_backend,
                    int(gate_fallback_used),
                    now,
                    job.raw_capture_id,
                ),
            )
            self._mark_outbox_complete(conn, job.id, now)

    @staticmethod
    def _mark_outbox_complete(
        conn: sqlite3.Connection, job_id: str, now: float
    ) -> None:
        cursor = conn.execute(
            """
            UPDATE outbox_jobs
            SET status = 'complete', lease_expires_at = NULL,
                last_error = '', updated_at = ?, completed_at = ?
            WHERE id = ? AND status = 'processing'
            """,
            (now, now, job_id),
        )
        if cursor.rowcount != 1:
            raise RuntimeError(f"outbox lease lost before completion: {job_id}")

    def complete_outbox_job(
        self, job: OutboxJob, memory_id: str, *, status: str = "complete"
    ) -> None:
        """Atomically complete the durable job and its raw capture."""
        now = time.time()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            conn.execute(
                """
                UPDATE raw_captures
                SET status = ?, memory_id = ?, error = '', updated_at = ?
                WHERE id = ?
                """,
                (status, memory_id, now, job.raw_capture_id),
            )
            self._mark_outbox_complete(conn, job.id, now)

    def fail_outbox_job(
        self,
        job: OutboxJob,
        error: str,
        *,
        max_attempts: int,
        retry_base_seconds: float,
        now: float | None = None,
    ) -> tuple[str, float]:
        """Schedule retry or atomically mark exhausted work dead."""
        failed_at = time.time() if now is None else now
        message = error[:1000]
        terminal = job.attempts >= max_attempts
        delay = (
            0.0
            if terminal
            else min(300.0, retry_base_seconds * (2 ** max(0, job.attempts - 1)))
        )
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            if terminal:
                cursor = conn.execute(
                    """
                    UPDATE outbox_jobs
                    SET status = 'dead', lease_expires_at = NULL,
                        last_error = ?, updated_at = ?, completed_at = ?
                    WHERE id = ? AND status = 'processing'
                    """,
                    (message, failed_at, failed_at, job.id),
                )
                raw_status = "failed"
                memory_status = "failed"
            else:
                cursor = conn.execute(
                    """
                    UPDATE outbox_jobs
                    SET status = 'retry', available_at = ?,
                        lease_expires_at = NULL, last_error = ?,
                        updated_at = ?, completed_at = NULL
                    WHERE id = ? AND status = 'processing'
                    """,
                    (failed_at + delay, message, failed_at, job.id),
                )
                raw_status = "pending"
                memory_status = "pending"
            if cursor.rowcount != 1:
                raise RuntimeError(f"outbox lease lost after failure: {job.id}")
            conn.execute(
                """
                UPDATE raw_captures
                SET status = ?, error = ?, updated_at = ?
                WHERE id = ?
                """,
                (raw_status, message, failed_at, job.raw_capture_id),
            )
            conn.execute(
                """
                UPDATE memories
                SET processing_status = ?, processing_error = ?
                WHERE id = ?
                """,
                (memory_status, message, job.raw_capture_id),
            )
        return ("dead" if terminal else "retry", delay)

    def retry_dead_outbox_job(self, job_id: str) -> bool:
        """Reset one dead job for an operator-requested retry."""
        now = time.time()
        with self._connect() as conn:
            conn.execute("BEGIN IMMEDIATE")
            row = conn.execute(
                "SELECT raw_capture_id FROM outbox_jobs WHERE id = ? AND status = 'dead'",
                (job_id,),
            ).fetchone()
            if row is None:
                return False
            raw_capture_id = str(row[0])
            conn.execute(
                """
                UPDATE outbox_jobs
                SET status = 'pending', attempts = 0, available_at = ?,
                    lease_expires_at = NULL, last_error = '',
                    updated_at = ?, completed_at = NULL
                WHERE id = ?
                """,
                (now, now, job_id),
            )
            conn.execute(
                """
                UPDATE raw_captures
                SET status = 'pending', error = '', updated_at = ?
                WHERE id = ?
                """,
                (now, raw_capture_id),
            )
            conn.execute(
                """
                UPDATE memories
                SET processing_status = 'pending', processing_error = ''
                WHERE id = ?
                """,
                (raw_capture_id,),
            )
        return True

    def outbox_job(self, job_id: str) -> dict | None:
        """Return non-content job metadata for diagnostics."""
        with self._connect() as conn:
            conn.row_factory = sqlite3.Row
            row = conn.execute(
                """
                SELECT id, raw_capture_id, event_type, status, attempts,
                       available_at, lease_expires_at, last_error,
                       created_at, updated_at, completed_at
                FROM outbox_jobs WHERE id = ?
                """,
                (job_id,),
            ).fetchone()
        return dict(row) if row else None

    def complete_raw_capture(
        self, capture_id: str, memory_id: str | None, *, status: str = "complete"
    ) -> None:
        """Compatibility helper for callers managing raw state directly."""
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE raw_captures
                SET status = ?, memory_id = ?, error = '', updated_at = ?
                WHERE id = ?
                """,
                (status, memory_id, time.time(), capture_id),
            )

    def fail_raw_capture(self, capture_id: str, error: str) -> None:
        """Compatibility helper for callers managing raw state directly."""
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE raw_captures
                SET status = 'failed', error = ?, updated_at = ?
                WHERE id = ?
                """,
                (error[:1000], time.time(), capture_id),
            )

    def reserve_event(self, event_id: str, stale_after: float = 300.0) -> bool:
        """Atomically reserve an external event for idempotent ingestion."""
        now = time.time()
        with self._connect() as conn:
            conn.execute("PRAGMA foreign_keys=ON")
            row = conn.execute(
                "SELECT status, updated_at FROM ingest_events WHERE event_id = ?",
                (event_id,),
            ).fetchone()
            if row is None:
                conn.execute(
                    """
                    INSERT INTO ingest_events
                        (event_id, status, created_at, updated_at)
                    VALUES (?, 'processing', ?, ?)
                    """,
                    (event_id, now, now),
                )
                return True
            if row[0] == "failed" or (
                row[0] == "processing" and row[1] < now - stale_after
            ):
                conn.execute(
                    """
                    UPDATE ingest_events
                    SET status = 'processing', attempts = attempts + 1,
                        last_error = '', updated_at = ?
                    WHERE event_id = ?
                    """,
                    (now, event_id),
                )
                return True
            return False

    def complete_event(self, event_id: str, capture_id: str | None) -> None:
        """Commit idempotency after either a memory or raw capture is durable."""
        now = time.time()
        with self._connect() as conn:
            conn.execute("PRAGMA foreign_keys=ON")
            memory_id = None
            raw_capture_id = None
            if capture_id:
                if conn.execute(
                    "SELECT 1 FROM memories WHERE id = ?", (capture_id,)
                ).fetchone():
                    memory_id = capture_id
                elif conn.execute(
                    "SELECT 1 FROM raw_captures WHERE id = ?", (capture_id,)
                ).fetchone():
                    raw_capture_id = capture_id
            conn.execute(
                """
                UPDATE ingest_events
                SET status = 'complete', memory_id = ?, raw_capture_id = ?,
                    updated_at = ?, processed_at = ?
                WHERE event_id = ?
                """,
                (memory_id, raw_capture_id, now, now, event_id),
            )

    def fail_event(self, event_id: str, error: str) -> None:
        """Release a failed event so JetStream redelivery can retry it."""
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE ingest_events
                SET status = 'failed', last_error = ?, updated_at = ?
                WHERE event_id = ?
                """,
                (error[:1000], time.time(), event_id),
            )

    def store(
        self,
        content: str,
        summary: str,
        category: str,
        tier: str,
        key_topics: list[str],
        source: str = "",
        embedding: Optional[bytes] = None,
        project: str = "",
        agent: str = "",
        user_id: Optional[str] = None,
        workspace_id: Optional[str] = None,
        project_id: Optional[str] = None,
        repository_id: Optional[str] = None,
        task_id: Optional[str] = None,
        session_id: Optional[str] = None,
        processing_status: str = "complete",
        memory_id: str | None = None,
    ) -> str:
        """
        Save a memory and return its ID.

        PATTERN: Auto-generated IDs
        We use UUIDs instead of auto-incrementing integers because:
        - No coordination needed between instances (safe for distributed systems)
        - Can generate ID before inserting (useful for embedding generation)
        - Can't guess other memory IDs from one ID (security)
        """
        now = time.time()
        mem_id = memory_id or f"mem_{int(now)}_{uuid.uuid4().hex[:6]}"

        # Calculate expiry based on tier
        ttl = self.ttl_config.get(tier, self.ttl_config["active"])
        expires_at = None if ttl == -1 else now + ttl
        lifecycle_state = {
            "cold": "ephemeral",
            "active": "active",
            "persist": "stable",
        }.get(tier, "active")

        with self._connect() as conn:
            conn.execute(
                """
                INSERT INTO memories (id, content, summary, category, tier, key_topics,
                                      source, embedding, created_at, accessed_at, expires_at,
                                      project, agent, processing_status,
                                      user_id, workspace_id, project_id, repository_id,
                                      task_id, session_id, lifecycle_state)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
                (
                    mem_id,
                    content,
                    summary,
                    category,
                    tier,
                    json.dumps(key_topics),
                    source,
                    embedding,
                    now,
                    now,
                    expires_at,
                    project,
                    agent,
                    processing_status,
                    user_id,
                    workspace_id,
                    project_id,
                    repository_id,
                    task_id,
                    session_id,
                    lifecycle_state,
                ),
            )

        logger.info(f"Stored memory {mem_id} (tier={tier}, category={category})")
        return mem_id

    def update_enrichment(
        self,
        mem_id: str,
        *,
        summary: str,
        category: str,
        tier: str,
        key_topics: list[str],
        processing_status: str = "complete",
        processing_error: str = "",
    ) -> None:
        """Apply extracted metadata after the raw memory is durable."""
        now = time.time()
        ttl = self.ttl_config.get(tier, self.ttl_config["active"])
        expires_at = None if ttl == -1 else now + ttl
        retention_review_at = now + self.ttl_config["active"]
        lifecycle_state = {
            "cold": "ephemeral",
            "active": "active",
            "persist": "stable",
        }.get(tier, "active")
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE memories
                SET summary = ?, category = ?, tier = ?, key_topics = ?,
                    expires_at = ?,
                    lifecycle_state = CASE
                        WHEN pinned = 1 THEN lifecycle_state ELSE ? END,
                    retention_review_at = ?,
                    processing_status = ?, processing_error = ?
                WHERE id = ?
                """,
                (
                    summary,
                    category,
                    tier,
                    json.dumps(key_topics),
                    expires_at,
                    lifecycle_state,
                    retention_review_at,
                    processing_status,
                    processing_error[:1000],
                    mem_id,
                ),
            )

    def set_embedding(
        self,
        mem_id: str,
        embedding: bytes,
        *,
        model: str,
        dimensions: int,
        content_hash: str,
    ) -> None:
        """Persist an exact-search embedding and its provenance."""
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE memories
                SET embedding = ?, embedding_model = ?,
                    embedding_dimensions = ?, embedding_content_hash = ?,
                    embedding_status = 'ready', embedding_updated_at = ?,
                    processing_error = '',
                    processing_status = 'complete'
                WHERE id = ?
                """,
                (
                    embedding,
                    model,
                    dimensions,
                    content_hash,
                    time.time(),
                    mem_id,
                ),
            )

    def mark_embedding_error(self, mem_id: str, error: str) -> None:
        with self._connect() as conn:
            conn.execute(
                """
                UPDATE memories
                SET embedding_status = 'failed', processing_error = ?,
                    embedding_updated_at = ?,
                    processing_status = 'failed'
                WHERE id = ?
                """,
                (error[:1000], time.time(), mem_id),
            )

    def stale_embeddings(self, model: str, limit: int = 100) -> list[dict]:
        """Return missing, failed, or content-changed embedding candidates."""
        with self._connect() as conn:
            conn.row_factory = sqlite3.Row
            rows = conn.execute(
                """
                SELECT id, content, embedding_model, embedding_content_hash,
                       embedding_status
                FROM memories
                WHERE embedding IS NULL OR embedding_status != 'ready'
                   OR embedding_model != ?
                ORDER BY created_at DESC
                LIMIT ?
                """,
                (model, limit),
            ).fetchall()
            candidates = [dict(row) for row in rows]
            remaining = limit - len(candidates)
            if remaining > 0:
                ready_rows = conn.execute(
                    """
                    SELECT id, content, embedding_model,
                           embedding_content_hash, embedding_status
                    FROM memories
                    WHERE embedding IS NOT NULL
                      AND embedding_status = 'ready'
                      AND embedding_model = ?
                    ORDER BY created_at DESC
                    LIMIT ?
                    """,
                    (model, max(remaining * 4, remaining)),
                ).fetchall()
                for row in ready_rows:
                    memory = dict(row)
                    digest = hashlib.sha256(
                        memory["content"].encode("utf-8")
                    ).hexdigest()
                    if digest != memory["embedding_content_hash"]:
                        candidates.append(memory)
                        if len(candidates) >= limit:
                            break
            return candidates[:limit]

    def search(
        self,
        query: str,
        category: Optional[str] = None,
        tier: Optional[str] = None,
        project: Optional[str] = None,
        agent: Optional[str] = None,
        limit: int = 10,
        include_cold: bool = False,
    ) -> list[dict]:
        """
        Search memories by text match and metadata filters.

        NOTE: This does keyword matching for now. Semantic search (via
        embeddings) is available via search_semantic() which uses
        cosine similarity on vector embeddings.
        """
        with self._connect() as conn:
            conn.row_factory = sqlite3.Row
            sql = "SELECT * FROM memories WHERE 1=1"
            params: list[object] = []

            # FTS-style keyword search across content and summary
            if query:
                sql += " AND (content LIKE ? OR summary LIKE ?)"
                params.extend([f"%{query}%", f"%{query}%"])

            if category:
                sql += " AND category = ?"
                params.append(category)
            if tier:
                sql += " AND tier = ?"
                params.append(tier)

            if project:
                sql += " AND project = ?"
                params.append(project)
            if agent:
                sql += " AND agent = ?"
                params.append(agent)
            # Filter out expired memories
            now = time.time()
            if include_cold:
                sql += """
                    AND ((expires_at IS NULL OR expires_at > ?)
                         OR lifecycle_state = 'cold')
                """
            else:
                sql += """
                    AND lifecycle_state NOT IN ('cold', 'archived')
                    AND (expires_at IS NULL OR expires_at > ?)
                """
            params.append(now)

            sql += " ORDER BY accessed_at DESC LIMIT ?"
            params.append(limit)

            rows = conn.execute(sql, params).fetchall()
            return [dict(r) for r in rows]

    def get(self, mem_id: str) -> Optional[dict]:
        """Get a memory by ID and record an explicit access."""
        with self._connect() as conn:
            conn.row_factory = sqlite3.Row
            row = conn.execute(
                "SELECT * FROM memories WHERE id = ?", (mem_id,)
            ).fetchone()
            if row:
                # Touch: update accessed_at for LRU during consolidation
                conn.execute(
                    "UPDATE memories SET accessed_at = ?, access_count = access_count + 1 WHERE id = ?",
                    (time.time(), mem_id),
                )
                return dict(row)
        return None

    def delete(self, mem_id: str) -> bool:
        """Delete a memory by ID."""
        with self._connect() as conn:
            cursor = conn.execute("DELETE FROM memories WHERE id = ?", (mem_id,))
            return cursor.rowcount > 0

    def consolidate(self) -> dict:
        """Demote expired memories reversibly; never delete automatically."""
        now = time.time()
        results = {
            "expired_deleted": 0,
            "expired_demoted": 0,
            "promoted": 0,
            "demoted": 0,
        }

        with self._connect() as conn:
            expired = conn.execute(
                """
                SELECT id, lifecycle_state FROM memories
                WHERE pinned = 0
                  AND lifecycle_state NOT IN ('cold', 'archived')
                  AND expires_at IS NOT NULL AND expires_at < ?
                ORDER BY id
                """,
                (now,),
            ).fetchall()
            for memory in expired:
                conn.execute(
                    """
                    INSERT INTO memory_lifecycle_audit (
                        id, memory_id, previous_state, new_state, reason,
                        actor_id, policy_version, created_at
                    ) VALUES (?, ?, ?, 'cold', 'retention_review',
                              NULL, 'utility-v1', ?)
                    """,
                    (
                        f"lifecycle_{uuid.uuid4().hex}",
                        memory[0],
                        memory[1],
                        now,
                    ),
                )
            cursor = conn.execute(
                """
                UPDATE memories
                SET lifecycle_state = 'cold', retention_review_at = ?
                WHERE pinned = 0
                  AND lifecycle_state NOT IN ('cold', 'archived')
                  AND expires_at IS NOT NULL AND expires_at < ?
                """,
                (now, now),
            )
            results["expired_demoted"] = cursor.rowcount
            conn.execute("UPDATE memories SET expires_at = NULL WHERE pinned = 1")

        logger.info(f"Consolidation: {results}")
        return results

    def operational_stats(self) -> dict:
        now = time.time()
        with self._connect() as conn:
            embedding = {
                row[0]: row[1]
                for row in conn.execute(
                    "SELECT embedding_status, COUNT(*) FROM memories GROUP BY embedding_status"
                )
            }
            processing = {
                row[0]: row[1]
                for row in conn.execute(
                    "SELECT processing_status, COUNT(*) FROM memories GROUP BY processing_status"
                )
            }
            events = {
                row[0]: row[1]
                for row in conn.execute(
                    "SELECT status, COUNT(*) FROM ingest_events GROUP BY status"
                )
            }
            outbox = dict.fromkeys(_OUTBOX_STATUSES, 0)
            outbox.update(
                {
                    row[0]: row[1]
                    for row in conn.execute(
                        "SELECT status, COUNT(*) FROM outbox_jobs GROUP BY status"
                    )
                }
            )
            oldest_due = conn.execute(
                """
                SELECT MIN(
                    CASE WHEN status = 'processing'
                         THEN lease_expires_at ELSE available_at END
                )
                FROM outbox_jobs
                WHERE (status IN ('pending', 'retry') AND available_at <= ?)
                   OR (status = 'processing' AND lease_expires_at <= ?)
                """,
                (now, now),
            ).fetchone()[0]
            active_leases = conn.execute(
                """
                SELECT COUNT(*) FROM outbox_jobs
                WHERE status = 'processing' AND lease_expires_at > ?
                """,
                (now,),
            ).fetchone()[0]
        return {
            "embeddings": embedding,
            "processing": processing,
            "ingest_events": events,
            "outbox": outbox,
            "outbox_oldest_due_seconds": (
                max(0.0, now - float(oldest_due)) if oldest_due is not None else 0.0
            ),
            "outbox_active_leases": active_leases,
        }

    def integrity_report(self, *, quick: bool = False) -> dict:
        """Check SQLite integrity, foreign keys, and graph orphan relations."""
        with self._connect() as conn:
            pragma = "quick_check" if quick else "integrity_check"
            integrity_rows = [
                str(row[0]) for row in conn.execute(f"PRAGMA {pragma}").fetchall()
            ]
            foreign_key_errors = [
                list(row) for row in conn.execute("PRAGMA foreign_key_check").fetchall()
            ]
            tables = {
                row[0]
                for row in conn.execute(
                    "SELECT name FROM sqlite_master WHERE type = 'table'"
                ).fetchall()
            }
            schema_version = conn.execute(
                "SELECT COALESCE(MAX(version), 0) FROM schema_migrations"
            ).fetchone()[0]
            orphans: dict[str, int] = {}
            if {"memory_entities", "memories", "entities"}.issubset(tables):
                orphans["memory_entities"] = conn.execute(
                    """
                    SELECT COUNT(*) FROM memory_entities me
                    LEFT JOIN memories m ON m.id = me.memory_id
                    LEFT JOIN entities e ON e.id = me.entity_id
                    WHERE m.id IS NULL OR e.id IS NULL
                    """
                ).fetchone()[0]
            if {"edges", "entities"}.issubset(tables):
                orphans["edges"] = conn.execute(
                    """
                    SELECT COUNT(*) FROM edges g
                    LEFT JOIN entities s ON s.id = g.source_id
                    LEFT JOIN entities t ON t.id = g.target_id
                    WHERE s.id IS NULL OR t.id IS NULL
                    """
                ).fetchone()[0]

        return {
            "integrity": integrity_rows,
            "foreign_key_errors": foreign_key_errors,
            "orphans": orphans,
            "schema_version": schema_version,
            "schema_current": schema_version == CURRENT_SCHEMA_VERSION,
            "ok": schema_version == CURRENT_SCHEMA_VERSION
            and integrity_rows == ["ok"]
            and not foreign_key_errors
            and not any(orphans.values()),
        }

    def count(self) -> int:
        """Return total number of memories (including expired)."""
        with self._connect() as conn:
            return conn.execute("SELECT COUNT(*) FROM memories").fetchone()[0]
